version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."

      - echo "Installing kubectl (Linux x86_64)..."
      - curl -LO https://s3.us-west-2.amazonaws.com/amazon-eks/1.33.0/2025-05-01/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl
      - kubectl version --client

      - echo "Confirming AWS CLI identity..."
      - aws sts get-caller-identity
      - echo "Testing cluster access..."
        kubectl auth can-i list nodes

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ms-analytics-service
      - IMAGE_TAG=latest
      - echo "REPOSITORY_URI=$REPOSITORY_URI"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo "Building Docker image for linux/arm64..."
      - docker buildx build --platform linux/arm64 -t $REPOSITORY_URI:$IMAGE_TAG . --push

  post_build:
    commands:
      - echo "Setting up kubeconfig with aws-iam-authenticator..."
      - aws eks update-kubeconfig --region ap-southeast-1 --name ms-analytics-cluster
  
      - echo "Testing cluster connection..."
      - kubectl get svc
  
      - echo "Deploying to EKS using rolling update..."
      - kubectl set image deployment/ms-analytics-deployment ms-analytics-service=$REPOSITORY_URI:$IMAGE_TAG
      - kubectl rollout status deployment/ms-analytics-deployment


artifacts:
  files:
    - imagedefinitions.json
