version: 0.2

phases:
  install:
    commands:
      - echo "Installing kubectl..."
      - curl -LO https://s3.us-west-2.amazonaws.com/amazon-eks/1.33.0/2025-05-01/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl
      - kubectl version --client

      - echo "Installing Helm..."
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - helm version

      - echo "Confirming AWS CLI identity..."
      - aws sts get-caller-identity

  post_build:
    commands:
      - echo "Setting kubeconfig..."
      - aws eks update-kubeconfig --region $AWS_REGION --name ms-lugx-cluster
      - echo "Deploying to $COLOR environment..."
      - helm upgrade --install analytics-blue ./helm -n analytics-service --create-namespace -f helm/values-blue.yaml --wait
      - echo "Switching stable ingress to analytics-$COLOR-svc..."
      - kubectl patch ingress analytics-stable-ingress -n analytics-service --type='json' -p="[{\"op\":\"replace\",\"path\":\"/spec/rules/0/http/paths/0/backend/service/name\",\"value\":\"analytics-$COLOR-svc\"}]"



artifacts:
  files:
    - imagedefinitions.json