{{- if .Values.stableIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: analytics-stable-ingress
  namespace: analytics-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.stableIngress.host }}
      http:
        paths:
          - path: /analytics(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.stableIngress.activeService }}
                port:
                  number: 80
{{- end }}
