apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ms-analytics.fullname" . }}-deployment
  labels:
    app: {{ include "ms-analytics.name" . }}
    {{- include "ms-analytics.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ include "ms-analytics.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ms-analytics.name" . }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3004
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV }}
            - name: CLICK_HOUSE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.config.clickhouseConfigMap }}
                  key: CLICK_HOUSE_URL
            - name: CLICK_HOUSE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.clickhouseSecret }}
                  key: CLICK_HOUSE_USERNAME
            - name: CLICK_HOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.clickhouseSecret }}
                  key: CLICK_HOUSE_PASSWORD
          readinessProbe:
            httpGet:
              path: /analytics/health
              port: 3004
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /analytics/health
              port: 3004
            initialDelaySeconds: 20
            periodSeconds: 10
