apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Values.app.name .Values.color | trim }}
  labels:
    app: {{ .Values.app.name }}
    color: {{ .Values.color }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        color: {{ .Values.color }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
            - name: CLICK_HOUSE_URL
              value: {{ .Values.env.CLICK_HOUSE_URL }}
            - name: CLICK_HOUSE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICK_HOUSE_USERNAME
            - name: CLICK_HOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICK_HOUSE_PASSWORD
            - name: PORT
              value: "{{ .Values.env.PORT }}"
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.container.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
