apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.app.name }}
    color: {{ .Values.color }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.name }}
    color: {{ .Values.color }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
