apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Values.app.name .Values.color | trim }}
  labels:
    app: {{ printf "%s-%s" .Values.app.name .Values.color | trim }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ printf "%s-%s" .Values.app.name .Values.color | trim }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
