apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-analytics-deployment
  labels:
    app: ms-analytics
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: ms-analytics
  template:
    metadata:
      labels:
        app: ms-analytics
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ms-analytics-service
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ms-analytics-service:${IMAGE_TAG}
          ports:
            - containerPort: 3001
          env:
           - name: NODE_ENV
             value: production
           - name: CLICK_HOUSE_URL
             valueFrom:
                configMapKeyRef:
                  name: clickhouse-config
                  key: CLICK_HOUSE_URL
           - name: CLICK_HOUSE_USERNAME
             valueFrom:
              secretKeyRef:
                name: clickhouse-secret
                key: CLICK_HOUSE_USERNAME
           - name: CLICK_HOUSE_PASSWORD 
             valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: CLICK_HOUSE_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 10

