apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: analytics-stable-ingress
  namespace: analytics-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: a3b59b55792154b8b9ddc81a5603c482-1330709055.ap-southeast-1.elb.amazonaws.com
    http:
      paths:
      - path: /analytics(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: analytics-blue-svc   # or analytics-green-svc depending on active deployment
            port:
              number: 80