app:
  name: analytics-service-app
color: green

replicaCount: 1

container:
  name: analytics-service-container
  port: 3004

image:
  repository: 241856856673.dkr.ecr.ap-southeast-1.amazonaws.com/ms-analytics-service
  tag: latest
  pullPolicy: Always

env:
  CLICK_HOUSE_URL: https://op6jbct4rg.ap-southeast-1.aws.clickhouse.cloud:8443
  NODE_ENV: production
  PORT: "3004"
  APP_VERSION: green


service:
  name: analytics-green-svc
  type: ClusterIP
  port: 80
  targetPort: 3004

ingress:
  enabled: true
  className: nginx
  host: 13.250.183.84.sslip.io
  paths:
    - path: /analytics
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

