app:
  name: analytics-service-app

color: blue

replicaCount: 1

container:
  name: analytics-service-container
  port: 3004

image:
  repository: 241856856673.dkr.ecr.ap-southeast-1.amazonaws.com/ms-analytics-service
  tag: latest
  pullPolicy: Always

env:
  CLICK_HOUSE_URL: https://op6jbct4rg.ap-southeast-1.aws.clickhouse.cloud:8443
  NODE_ENV: production
  PORT: "3004"
  APP_VERSION: blue


service:
  name: analytics-blue-svc
  type: ClusterIP
  port: 80
  targetPort: 3004

ingress:
  enabled: true
  className: nginx
  host: a3b59b55792154b8b9ddc81a5603c482-1330709055.ap-southeast-1.elb.amazonaws.com
  paths:
    - path: /analytics
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
